### ISSUE TITLE
Problem in generation of FTAN curves

### ISSUE THREAD

**Issue by Akashkharita** [ThomasLecocq/msnoise-tomo#26]
Hi Thomas, 

I had created the tomo_sac files, populated the station table with correct coordinates and elevations. then I ran
msnoise p tomo 
I was trying to plot the ftan curves and I got this error- 

(base) C:\Users\akash\msnoise__testing>msnoise p tomo iftan

it opened a gui, but when I selected the TOMO_SAC files  I got this error- 
----------------------------------------------------------------------------------------------------------------------------------------------

Running FTAN the first time: C:\Users\akash\msnoise__testing\TOMO_SAC\03\ZZ\AK_GREN_AK_GRES_MEAN.sac

fmin=0.1, fmax=1, nfreqs=40
bmin=0.0022, bmax=0.025
ampMin=0.05
vgMin=0.5 vgMax=5
disp: no
diag: Period - Vgroup
out: enable (matrix)
max: 0.1
write amplitude
write phase
write FT
write TV
C:\Users\akash\anaconda3\lib\site-packages\msnoise_tomo-0.1b0-py3.7-win-amd64.egg\msnoise_tomo\ftan_call.py:28: UserWarning: loadtxt: Empty input file: "write_amp.txt"
  amp = np.loadtxt('write_amp.txt') # this the FTAN matrix
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\akash\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\akash\anaconda3\lib\site-packages\msnoise_tomo-0.1b0-py3.7-win-amd64.egg\msnoise_tomo\iftan.py", line 119, in process
    ydata)
  File "C:\Users\akash\anaconda3\lib\site-packages\msnoise_tomo-0.1b0-py3.7-win-amd64.egg\msnoise_tomo\ftan_call.py", line 32, in pickgroupdispcurv
    index = np.unravel_index(np.argmax(amp), amp.shape)
  File "<__array_function__ internals>", line 6, in argmax
  File "C:\Users\akash\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 1186, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "C:\Users\akash\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

------------------------------------------------------------------------------------------------------------------------------------------------

Here is the output of conda list - 
[list.txt](https://github.com/ThomasLecocq/msnoise-tomo/files/6677252/list.txt)

**Comment by Akashkharita** [comment]
The problem is solved by correcting the station coordinates. (DEG instead of UTM)
