### ISSUE TITLE
msnoise-tomo installation from scratch

### ISSUE THREAD

**Issue by dylanmikesell** [ThomasLecocq/msnoise-tomo#8]
Hi @ThomasLecocq 

I am planning to help my students and make some modifications to msnoise-tomo source code...and fix our own issues. 

The previous changes (issue #4) were simple and I didn't need to test things. I am now trying to do an installation of msnoise-tomo from scratch in my forked version of the repo.
I am running python 3.8, obspy 1.2.1, and setuptools 47.3.1
I cannot get around this error, and I wonder if you have dealt with this already.
I am running

$ python setup.py install 

and getting the following output

/Users/dmikesell/GIT/msnoise-tomo
/Users/dmikesell/GIT/msnoise-tomo
Traceback (most recent call last):
  File "setup.py", line 229, in <module>
    setupPackage()
  File "setup.py", line 200, in setupPackage
    features=add_features(),
  File "setup.py", line 73, in add_features
    class ExternalLibFeature(setuptools.Feature):
AttributeError: module 'setuptools' has no attribute 'Feature'

I tried running $ python setup.py clean --all and then rerunning the install. Same problem. Have you had this problem with setupPackage() before? I have tried a number of install things so far and none have worked.

Any thoughts? I found this on the setuptools package page: https://setuptools.readthedocs.io/en/latest/history.html#v46-0-0.

Do we just remove `features=add_features(),` on line 200 in setup.py? I tried commenting this line out, but still got an error when trying to do the gcc compilation. Wondering if I need to go back to python 3.6 perhaps?

**Comment by ThomasLecocq** [comment]
there is an issue with the latest versions of setuptools indeed, I need to change the Feature stuff, see #6 where there is a link to the obspy solution for that.
